"""Provider-, persistence-, and filesystem-neutral media contracts."""

from .audio import build_audio_transcript_batch, build_video_transcript_batch
from .builders import (
    MEDIA_RESOURCE_KINDS,
    RESOURCE_AUDIO,
    RESOURCE_VIDEO,
    FrameBatchBuilderInput,
    MediaResourceDescriptor,
    TranscriptBatchBuilderInput,
)
from .common import JSONScalar, JSONValue, canonical_json
from .contract import MEDIA_CONTRACT_VERSION
from .events import (
    MEDIA_EVENT_NAMES,
    MediaEvent,
    MediaEventCategory,
    MediaEventStatus,
    MediaOperation,
    MediaResourceKind,
)
from .fingerprints import (
    AggregationFingerprint,
    EmbeddingFingerprint,
    GrouperFingerprint,
    NormalizationFingerprint,
    ProducerFingerprint,
    TokenCounterFingerprint,
)
from .grouper import (
    GROUPER_ALGORITHM,
    JOIN_POLICY,
    UNSPLITTABLE_FLAG,
    UNSPLITTABLE_REJECT,
    GroupingMetrics,
    GroupingPolicyVariant,
    GroupingVariantResult,
    TimedGroupingError,
    TimedGroupingResult,
    group_timed_atoms,
    provisional_abc_policies,
    run_grouping_variants,
)
from .identifiers import (
    ID_ATOM,
    ID_FRAME,
    ID_PASSAGE,
    ID_REPRESENTATION,
    ID_RESOURCE,
    ID_WHOLE,
    atom_id,
    frame_id,
    passage_id,
    representation_id,
    resource_id,
    stable_media_id,
    validate_media_id,
    whole_resource_id,
)
from .locators import (
    LOCATOR_TIME_SEGMENT,
    LOCATOR_VIDEO_FRAME,
    LOCATOR_WHOLE_MEDIA,
    TRACK_AUDIO,
    TRACK_VIDEO,
    TimeSegmentLocator,
    VideoFrameLocator,
    WholeMediaLocator,
)
from .policies import (
    OVERFLOW_CALLER_SPLIT,
    OVERFLOW_REJECT,
    TextNormalizationPolicy,
    TimedChunkingPolicy,
    WholeResourceTextPolicy,
)
from .ports import TokenCounter
from .records import (
    REPRESENTATION_AUDIO_TRANSCRIPT,
    REPRESENTATION_FRAME_CAPTION,
    REPRESENTATION_TIMED_PASSAGE,
    TOKEN_COUNT_ESTIMATED,
    TOKEN_COUNT_EXACT,
    FrameCaptionArtifact,
    FrameCaptionObservation,
    TimedPassage,
    TimedTextAtom,
    TokenCount,
    TranscriptArtifact,
)

__all__ = [
    "AggregationFingerprint",
    "EmbeddingFingerprint",
    "FrameBatchBuilderInput",
    "FrameCaptionArtifact",
    "FrameCaptionObservation",
    "GROUPER_ALGORITHM",
    "GrouperFingerprint",
    "GroupingMetrics",
    "GroupingPolicyVariant",
    "GroupingVariantResult",
    "ID_ATOM",
    "ID_FRAME",
    "ID_PASSAGE",
    "ID_REPRESENTATION",
    "ID_RESOURCE",
    "ID_WHOLE",
    "JOIN_POLICY",
    "JSONScalar",
    "JSONValue",
    "LOCATOR_TIME_SEGMENT",
    "LOCATOR_VIDEO_FRAME",
    "LOCATOR_WHOLE_MEDIA",
    "MEDIA_CONTRACT_VERSION",
    "MEDIA_EVENT_NAMES",
    "MEDIA_RESOURCE_KINDS",
    "MediaEvent",
    "MediaEventCategory",
    "MediaEventStatus",
    "MediaOperation",
    "MediaResourceDescriptor",
    "MediaResourceKind",
    "NormalizationFingerprint",
    "OVERFLOW_CALLER_SPLIT",
    "OVERFLOW_REJECT",
    "ProducerFingerprint",
    "REPRESENTATION_AUDIO_TRANSCRIPT",
    "REPRESENTATION_FRAME_CAPTION",
    "REPRESENTATION_TIMED_PASSAGE",
    "RESOURCE_AUDIO",
    "RESOURCE_VIDEO",
    "TOKEN_COUNT_ESTIMATED",
    "TOKEN_COUNT_EXACT",
    "TRACK_AUDIO",
    "TRACK_VIDEO",
    "TextNormalizationPolicy",
    "TimeSegmentLocator",
    "TimedChunkingPolicy",
    "TimedGroupingError",
    "TimedGroupingResult",
    "TimedPassage",
    "TimedTextAtom",
    "TokenCount",
    "TokenCounter",
    "TokenCounterFingerprint",
    "TranscriptArtifact",
    "TranscriptBatchBuilderInput",
    "UNSPLITTABLE_FLAG",
    "UNSPLITTABLE_REJECT",
    "VideoFrameLocator",
    "WholeMediaLocator",
    "WholeResourceTextPolicy",
    "atom_id",
    "build_audio_transcript_batch",
    "build_video_transcript_batch",
    "canonical_json",
    "frame_id",
    "group_timed_atoms",
    "passage_id",
    "provisional_abc_policies",
    "representation_id",
    "resource_id",
    "run_grouping_variants",
    "stable_media_id",
    "validate_media_id",
    "whole_resource_id",
]
