from __future__ import annotations

import mdrack_core
import mdrack_core.application as core_application
import mdrack_core.domain as core_domain
import mdrack_core.ports as core_ports

ROOT_EXPORTS = (
    "BranchExecutionError",
    "BranchScopeOverride",
    "CORE_EVENT_NAMES",
    "CORE_CONTRACT_VERSION",
    "CatalogExecutionError",
    "CatalogPort",
    "CoreError",
    "Degradation",
    "DegradationCategory",
    "EmbeddingSpaceRecord",
    "ErrorCategory",
    "FACET_ORIGIN_CLASSIFIER",
    "FACET_ORIGIN_EXTRACTOR",
    "FACET_ORIGIN_SOURCE",
    "FACET_ORIGIN_USER",
    "Facet",
    "JSONScalar",
    "JSONValue",
    "LexicalBranch",
    "LexicalSearchPort",
    "LifecycleStatus",
    "Locator",
    "METRIC_COSINE",
    "METRIC_DOT",
    "METRIC_L2",
    "MODALITY_AUDIO",
    "MODALITY_IMAGE",
    "MODALITY_TEXT",
    "MODALITY_VIDEO",
    "PreparedResourceBatch",
    "RankKind",
    "REPRESENTATION_AUDIO_TRANSCRIPT",
    "REPRESENTATION_CAPTION_TEXT",
    "REPRESENTATION_FRAME_CAPTION",
    "REPRESENTATION_OCR_TEXT",
    "REPRESENTATION_RETRIEVAL_TEXT",
    "REPRESENTATION_TRANSCRIPT_TEXT",
    "REPRESENTATION_VISUAL",
    "REDACTED",
    "RESOURCE_AUDIO",
    "RESOURCE_DOCUMENT",
    "RESOURCE_IMAGE",
    "RESOURCE_VIDEO",
    "RankedCandidate",
    "RepresentationRecord",
    "ResourceFacet",
    "ResourceReadPort",
    "ResourceRecord",
    "ResourceWritePort",
    "SafeEvent",
    "SafeFingerprint",
    "SearchPort",
    "SearchRequest",
    "SearchResult",
    "SearchResultItem",
    "SearchScope",
    "SearchUnitRecord",
    "ScoreKind",
    "SimilarityRequest",
    "SimilarityResult",
    "TARGET_RESOURCE",
    "TARGET_UNIT",
    "TOKEN_COUNT_ESTIMATED",
    "TOKEN_COUNT_EXACT",
    "UNIT_FRAME",
    "UNIT_PAGE",
    "UNIT_REGION",
    "UNIT_TEXT_CHUNK",
    "UNIT_TIME_SEGMENT",
    "UNIT_WHOLE_RESOURCE",
    "VectorBranch",
    "VectorRecord",
    "VectorSearchPort",
    "canonical_json",
    "emit_event",
    "safe_fingerprint",
)

DOMAIN_EXPORTS = (
    "BranchExecutionError",
    "BranchScopeOverride",
    "CatalogExecutionError",
    "CoreError",
    "Degradation",
    "DegradationCategory",
    "EmbeddingSpaceRecord",
    "ErrorCategory",
    "FACET_ORIGIN_CLASSIFIER",
    "FACET_ORIGIN_EXTRACTOR",
    "FACET_ORIGIN_SOURCE",
    "FACET_ORIGIN_USER",
    "Facet",
    "JSONScalar",
    "JSONValue",
    "LexicalBranch",
    "Locator",
    "METRIC_COSINE",
    "METRIC_DOT",
    "METRIC_L2",
    "MODALITY_AUDIO",
    "MODALITY_IMAGE",
    "MODALITY_TEXT",
    "MODALITY_VIDEO",
    "PreparedResourceBatch",
    "RankKind",
    "REPRESENTATION_AUDIO_TRANSCRIPT",
    "REPRESENTATION_CAPTION_TEXT",
    "REPRESENTATION_FRAME_CAPTION",
    "REPRESENTATION_OCR_TEXT",
    "REPRESENTATION_RETRIEVAL_TEXT",
    "REPRESENTATION_TRANSCRIPT_TEXT",
    "REPRESENTATION_VISUAL",
    "RESOURCE_AUDIO",
    "RESOURCE_DOCUMENT",
    "RESOURCE_IMAGE",
    "RESOURCE_VIDEO",
    "RankedCandidate",
    "RepresentationRecord",
    "ResourceFacet",
    "ResourceRecord",
    "SearchRequest",
    "SearchResult",
    "SearchResultItem",
    "SearchScope",
    "SearchUnitRecord",
    "ScoreKind",
    "SimilarityRequest",
    "SimilarityResult",
    "TARGET_RESOURCE",
    "TARGET_UNIT",
    "TOKEN_COUNT_ESTIMATED",
    "TOKEN_COUNT_EXACT",
    "UNIT_FRAME",
    "UNIT_PAGE",
    "UNIT_REGION",
    "UNIT_TEXT_CHUNK",
    "UNIT_TIME_SEGMENT",
    "UNIT_WHOLE_RESOURCE",
    "VectorBranch",
    "VectorRecord",
    "canonical_json",
)

APPLICATION_EXPORTS = (
    "CoreIndexingService",
    "FusedCandidate",
    "FusionBranch",
    "FusionCandidate",
    "ResourceDiscoveryService",
    "RetrievalService",
    "weighted_rrf",
)

PORT_EXPORTS = (
    "CatalogPort",
    "LexicalSearchPort",
    "ResourceReadPort",
    "ResourceWritePort",
    "SearchPort",
    "VectorSearchPort",
)


def test_core_contract_version_and_ordered_public_exports_are_frozen() -> None:
    assert mdrack_core.CORE_CONTRACT_VERSION == "1.0.0-rc.1"
    assert mdrack_core.__all__ == ROOT_EXPORTS
    assert core_domain.__all__ == DOMAIN_EXPORTS
    assert core_application.__all__ == APPLICATION_EXPORTS
    assert core_ports.__all__ == PORT_EXPORTS
    assert all(hasattr(mdrack_core, name) for name in ROOT_EXPORTS)
